version: '3.3'
services:
  app:
    image: wordpress
    ports:
     - 80:80
  
  db-client:
    image: phpmyadmin
    ports:
     - 8080:80

  mailserver:
    image: axllent/mailpit
    ports:
     - 8025:8025
     - 1025:1025

  db:
    image: mysql
    volumes:
     - db-data:/var/lib/mysql
    ports:
     - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'

volumes:
  db-data: