version: '3.3'
services:
  app:
    image: stenote/nginx-hostname
    deploy:
      replicas: 3
    ports:
     - 80:80
  db:
    image: mysql
    ports:
     - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'